# Generated by Django 4.2 on 2023-05-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(editable=False, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_valid', models.IntegerField(default=14)),
            ],
        ),
    ]
