# Generated by Django 4.2 on 2023-05-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_valid', models.IntegerField(default=25)),
                ('is_paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SendEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=255)),
                ('topic', models.CharField(max_length=255)),
                ('toEmail', models.CharField(max_length=255)),
                ('toName', models.CharField(max_length=255)),
                ('fromName', models.CharField(max_length=255)),
                ('fromEmail', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('email_body', models.CharField(max_length=255)),
            ],
        ),
    ]
