# Generated by Django 4.2 on 2023-05-31 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_valid', models.IntegerField(default=25)),
                ('is_paid', models.BooleanField(default=False)),
            ],
        ),
    ]
