# Generated by Django 4.2 on 2023-05-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_apikey_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=255)),
                ('topic', models.CharField(default='EditorMailComponent', max_length=255)),
                ('toEmail', models.CharField(max_length=255)),
                ('toName', models.CharField(max_length=255)),
                ('fromName', models.CharField(max_length=255)),
                ('fromEmail', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('email_body', models.CharField(max_length=255)),
            ],
        ),
    ]
