# Generated by Django 4.2 on 2023-05-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_sendemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendemail',
            name='topic',
            field=models.CharField(max_length=255),
        ),
    ]
