# Generated by Django 4.2 on 2023-05-29 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_sendemail_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='is_valid',
            field=models.IntegerField(default=3),
        ),
    ]
